### ISSUE TITLE
Complete request & response for atleast 4xx & 5xx errors

### ISSUE THREAD

**Issue by mssach** [DataDog/jmeter-datadog-backend-listener#19]
It will be good if we have complete request & response for atleast 4xx & 5xx errors.

most probably there will be just status code & message in response format, which will not be that heavy on data volume side to pull whenever it is 4xx/5xx.

This will make sure there is no need of again configuring another tool for log analysis to view why the error is happening.

**Comment by hithwen** [comment]
Hallo @mssach, which integration are you referring to?

**Comment by sarah-witt** [comment]
Hello @mssach, thank you for submitting this feature request. We are looking into implementing this, but want to know if the following approach will fulfill your use case: 

We add an option to send enriched HTTP request and response data upon failure in logs. When enabled, the message of the logs would look like:

```
message: {original error message}

response data: {long stack trace.. etc}

request headers: {headers… }
```
