### ISSUE TITLE
when we set includeSubResults to true or blank is not sending all metrics its supposed to send

### ISSUE THREAD

**Issue by PavanMudigondaTR** [DataDog/jmeter-datadog-backend-listener#34]
**Describe the bug**

When I enter “includeSubresults” to “true” or BLANK then I am only able to see 5 Metrics flowing into DataDog. When I select “includeSubresults” to “false”  then 29 Metrics + 5 Logs Entries are flowing in to DataDog. I was trying to understand this from many days and finally I came to this conclusion.  Today morning I contacted DataDog Support Team  via chat but they couldn’t understand my issue.  After lot of hard work today I was able to identify what’s causing it. I would really appreciate if you someone could fix this as soon as possible as many of our teams are looking for this.

Organization: Thomson Reuters. Please message or email privately if you need our DataDog Account name to verify.

**To Reproduce**
1. Set Config as per my screenshot. 
2. Run test
3. you will see only 5 metrics appearing in Datadog from jmeter

**Expected behavior**
I would expect to see all 29 Metrics + 5 Logs Entries even when I set  “includeSubresults”  to true. Additionally I would expect it to send Sub Results as that’s what its supposed to do.

**Screenshots**
<img width="1054" alt="image" src="https://user-images.githubusercontent.com/86745613/205410561-095dfbfa-869d-4bbc-a76a-75c3841a997f.png">

**Desktop (please complete the following information):**
 - OS: UBUNTU LATEST 22 / CODEBUILD IMAGE 6.0
 - Version 22

**Additional context**
29 Metrics I refer to are here:-
<img width="924" alt="image" src="https://user-images.githubusercontent.com/86745613/205686047-279c715d-8380-4975-b8ef-7b9bab50acd0.png">

5 Logs I refer to are here:-
<img width="1231" alt="image" src="https://user-images.githubusercontent.com/86745613/205686103-e2bd8ebc-b846-4238-8877-a0de076fb43f.png">

**Comment by alopezz** [comment]
Apologies for the delay in dealing with your issue. It does look like the current implementation of this configuration option includes _only_ subresults (i.e. it excludes the main results). A fix will be available shortly.

**Comment by alopezz** [comment]
I've made a beta release for the potential fix: https://github.com/DataDog/jmeter-datadog-backend-listener/releases/tag/0.3.1-beta-1

Can you try it out and see if it behaves as expected?

**Comment by PavanMudigonda** [comment]
> 

will test and get back to you Monday tomorrow.

**Comment by PavanMudigondaTR** [comment]
> I've made a beta release for the potential fix: https://github.com/DataDog/jmeter-datadog-backend-listener/releases/tag/0.3.1-beta-1
> 
> Can you try it out and see if it behaves as expected?

I got this error and it seems to be due to datadog listener. I will continue to test today and keep you posted. meanwhile please take a look at this error.

<img width="1060" alt="image" src="https://user-images.githubusercontent.com/86745613/208703393-8fb3d2a8-a736-4be6-8158-80227f9eec72.png">

**Comment by alopezz** [comment]
I've been doing some research, and the exception comes from [here](https://github.com/apache/jmeter/blob/7153c74dd0e860d0ca3825cc5a23e976e0242b6e/src/components/src/main/java/org/apache/jmeter/visualizers/backend/BackendListener.java#L127-L131).

Only line 966 in the log you shared looks related to the `DatadogBackendClient`, and it seems to be a problem with the dynamic loading of the class, which to me points at some installation issue as a possible reason. The closest I've got to reproducing the issue has been by trying to remove the jar file after adding the backend listener to a test plan. That produces the same error message, but is followed by details of the exception, which for some reason are missing from your log (and would be really helpful).

Can you detail the steps you took to update?

**Comment by PavanMudigondaTR** [comment]
> I've been doing some research, and the exception comes from [here](https://github.com/apache/jmeter/blob/7153c74dd0e860d0ca3825cc5a23e976e0242b6e/src/components/src/main/java/org/apache/jmeter/visualizers/backend/BackendListener.java#L127-L131).
> 
> Only line 966 in the log you shared looks related to the `DatadogBackendClient`, and it seems to be a problem with the dynamic loading of the class, which to me points at some installation issue as a possible reason. The closest I've got to reproducing the issue has been by trying to remove the jar file after adding the backend listener to a test plan. That produces the same error message, but is followed by details of the exception, which for some reason are missing from your log (and would be really helpful).
> 
> Can you detail the steps you took to update?

@alopezz 
Sorry, my bad. After doing some testing. I figured this error is not specific to datadog listener. I couldn’t test the original reported bug yet. I will test and and get back to you by end of next week.

**Comment by PavanMudigondaTR** [comment]
@alopezz

Sorry for the delay in my response back. Just back from holidays and started testing this !

Your beta fix is perfectly working fine. I request you to make the release official !

**Comment by PavanMudigondaTR** [comment]
@alopezz  great work. we are using 0.3.1  and its working fine. thanks a lot !
